---
- hosts: server_ansible
  become: true

  handlers:
    - name: restart ssh
      service:
        name: sshd

  tasks:
    - name: Marking ssh as default port 2222 to make server secure
      seport:
       ports: 2222       
       proto: tcp
       setype: ssh_port_t
       state: present
    - name: Making ssh more secure
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      
      with_items:
        - regexp: "^PasswordAuthentication"
          line: "PasswordAuthenticaion no"
        - regexp: "^PermitRootLogin"
          line: "PermitRootLogin no"
        - regexp: "^Port"
          line: "Port 2222"
      
      notify: restart ssh 
    
    - name: Remove unused packages
      yum: name={{ item }} state=absent purge=yes
      with_items:
        - telnet
        - mailutils
        - nano 
    - name: Configure open ports with ufw.
      ufw:
        rule: "{{ item.rule }}"
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      with_items:
        - { rule: 'allow', port: 22, proto: 'tcp' }
        - { rule: 'allow', port: 80, proto: 'tcp' }
        - { rule: 'allow', port: 123, proto: 'udp' }

    - name: Configure default incoming/outgoing rules with ufw.
      ufw:
        direction: "{{ item.direction }}"
        policy: "{{ item.policy }}"
          state: enabled
      with_items:
        - { direction: outgoing, policy: allow }
        - { direction: incoming, policy: deny }

    - name: Configure open ports with firewalld.
      firewalld:
        state: "{{ item.state }}"
        port: "{{ item.port }}"
        zone: external
        immediate: yes
        permanent: yes
      with_items:
        - { state: 'enabled', port: '2222/tcp' }
        - { state: 'enabled', port: '80/tcp' }  
        - { state: 'enabled', port: '123/udp' }

